### ISSUE TITLE
Pip By Monday

### ISSUE THREAD

**Issue by brettforbes** [os-threat/Stix-ORM#24]
The aim is for Denis to have:
- Stix, Attack objects and Feeds working on pip by monday, check paths issue for type factory
- Loading of Attack data working on pip by Monday

**Comment by andrewgin** [comment]
Is there anything blocking this at the moment? As far as I know, all it needs is publishing to pypi as the `pyproject.toml` is all ready to go

**Comment by dfjosullivan** [comment]
A passing build. Example attack test running

**Comment by dfjosullivan** [comment]
Pip is published by creating a new release
