### ISSUE TITLE
pip packaging

### ISSUE THREAD

**Issue by priamai** [os-threat/Stix-ORM#3]
I will setup structure for pip packaging.

**Comment by priamai** [comment]
@andrewgin we need to restructure the code base to be able to save it on pypi. This was my previous effort for reference.
https://pypi.org/project/stixorm/
https://github.com/priamai/stixorm

**Comment by dfjosullivan** [comment]
@andrewgin Could you look at this one

**Comment by dfjosullivan** [comment]
This is completed
